name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+-*'

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    strategy:
      max-parallel: 20
      matrix:
        image:
          - almalinux_8
          - almalinux_9

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build RPM
        run: |
          ./build $(echo ${BUILD_IMAGE} | sed 's/_/:/g')
          echo "##[set-output name=release-tag;]$(echo ${{ github.ref }} | sed -e 's|refs/tags/||g')"

      - name: Upload Assets
        uses: AButler/upload-release-assets@3d6774fae0ed91407dc5ae29d576b166536d1777 # v3.0
        with:
          files: "rpmbuild/SRPMS/*.rpm;rpmbuild/RPMS/*/*.rpm"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.build_rpm.outputs.release-tag }}
