name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v[0-9]+.[0-9]+-*'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 20
      matrix:
        image:
          - almalinux_8
          - almalinux_9

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build RPM
        run: |
          ./build $(echo ${BUILD_IMAGE} | sed 's/_/:/g')

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.image }}
          path: rpmbuild/**/*.rpm
